# Inserts blank line between shell prompts.
add_newline = false
# Timeout for starship to scan files (in milliseconds).
scan_timeout = 200

format = """
[ ](fg:color1 bg:color3)\
$time\
[ ](fg:color3 bg:color4)\
$sudo\
$username\
$os\
$hostname\
[ ](fg:color2 bg:color4)\
$battery\
[ ](fg:color4 bg:color5)\
$directory\
[ ](fg:color5 bg:color6)\
$git_branch\
$git_status\
[ ](fg:color6 bg:color7)\
$c\
$golang\
$nodejs\
$php\
$python\
$rust\
[ ](fg:color7 bg:color8)\
$cmd_duration\
[ ](fg:color8)\
\n$character"""

palette = 'tokyo'

[palettes.tokyo]
repo_root = '#e3e5e5'
warning = '#ff7700'
danger = '#ff0000'
color0 = '#e3e5e5'
color1 = '#30C5D2'
color2 = '#33ABC3'
color3 = '#3791B4'
color4 = '#3A77A5'
color5 = '#3D5E96'
color6 = '#404487'
color7 = '#442A78'
color8 = '#471069'

[aws]
disabled = true
symbol = "  "

[battery]
#full_symbol = '󰁹'
charging_symbol = '󰂄'
#discharging_symbol = '󱟟'
discharging_symbol = '󱟤'
unknown_symbol = '󰂁' # plugged-in, not charging but not full
#empty_symbol = '󰂎'
empty_symbol = '󰂃'
format = '[$symbol ]($style)'

[[battery.display]]
style = 'fg:color0 bg:color4'
threshold = 100

[[battery.display]]
style = 'fg:warning bg:color4'
threshold = 40

[[battery.display]]
style = 'fg:danger bg:color4'
threshold = 20

[buf]
disabled = true
symbol = " "

[c]
disabled = false
symbol = ""
style = "fg:color0 bg:color7"
format = '[$symbol($version)]($style)'

[cmd_duration]
disabled = false
min_time = 0
style = "fg:color0 bg:color8"
format = '[$duration]($style)'

[conda]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[directory]
read_only = "󰌾"
style = "fg:color0 bg:color5"
repo_root_style = "fg:repo_root bold bg:color5"
read_only_style = "fg:color0 bg:color5"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
'Applications' = ''
'Backups' = '󰁯'
'Books' = ''
'Documents' = '󰈙'
'Downloads' = ''
'Music' = ''
'Notes' = ''
'Pictures' = ''
'Projects' = '󱌣'
'Videos' = ''

[docker_context]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[fossil_branch]
disabled = true
symbol = " "

[git_branch]
disabled = false
#symbol = ' '
symbol = '󰊢'
style = "fg:color0 bg:color6"
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
disabled = false
style = "fg:color0 bg:color6"
format = '[\[($all_status$ahead_behind)\]]($style)'
#conflicted = "⚔️ "
ahead = '⇡×${count}'
behind = '⇣×${count}'
#diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "󰞋×${count}"
stashed = "×${count}"
modified = "󰏬×${count}"
staged = "󰋠×${count}"
renamed = "󰛂×${count}"
deleted = "×${count}"

[golang]
disabled = false
symbol = ""
style = "fg:color0 bg:color7"
not_capable_style = "fg:danger bg:color7"
format = '[$symbol($version)]($style)'

[guix_shell]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = "⌘ "

[hg_branch]
disabled = true
symbol = " "

[hostname]
disabled = false
ssh_only = false
ssh_symbol = ""
style = 'fg:color0 bg:color4'
format = '[$hostname$ssh_symbol]($style)'

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[lua]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[meson]
disabled = true
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = false
symbol = ""
style = "fg:color0 bg:color7"
not_capable_style = "fg:danger bg:color7"
format = '[$symbol($version)]($style)'

[os]
disabled = false
style = 'fg:color0 bg:color4'
format = '[$symbol]($style)'

[os.symbols]
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = "󰍲"

[package]
symbol = "󰏗 "

[pijul_channel]
disabled = true
symbol = "🪺 "

[php]
disabled = false
symbol = ""
style = "fg:color0 bg:color7"
format = '[$symbol($version)]($style)'

[python]
disabled = false
symbol = ''
style = "fg:color0 bg:color7"
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)'

[rlang]
disabled = true
symbol = "󰟔 "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = false
symbol = ""
style = "fg:color0 bg:color7"
format = '[$symbol($numver)]($style)'

[scala]
disabled = true
symbol = " "

[spack]
disabled = true
symbol = "🅢 "

[sudo]
disabled = false
symbol = '󱄼'
style = 'fg:color0 bg:color4'
format = '[$symbol]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:color0 bg:color3"
format = '[$time ]($style)'

[username]
disabled = false
style_root = 'fg:danger bg:color4'
style_user = 'fg:color0 bg:color4'
format = '[$user]($style)'
